uploaded
raterCss
	^ '
	.currentMetric{
       border: 2px solid rgb(244, 244, 52) !important;
       background: rgb(253, 255, 134) !important;
	}
	.currentMetric .panel-heading{
 	    background: rgb(230, 218, 48) !important;
	}
	.currentMetric .panel-body{
 	    background: rgb(254, 255, 217) !important;
	}
	.currentMetric .panel-body input{
		border: 1px solid rgb(187, 182, 7) !important;
	}
	'